=== iammisc/zynx-se-bootcamp/xml/firstModularSolution.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:first="http://www.example.com/modularinclude"
    xmlns:import="http://www.example.com/modularimport"
    targetNamespace="http://www.example.com/modularinclude"
    elementFormDefault="qualified">
    
    <include schemaLocation="secondModularSolution.xsd"/>
    <import namespace="http://www.example.com/modularimport" schemaLocation="thirdModularSolution.xsd"/>
    
    <element name="blogs">
        <complexType>
            <sequence>
                <element name="blog" type="first:BlogType" minOccurs="1" maxOccurs="unbounded"/> 
            </sequence>
        </complexType>
    </element>
    
    <complexType name="BlogType">
        <sequence>
            <element name="blogTitle" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="blogger" minOccurs="0" maxOccurs="1">
                <complexType>
                    <sequence>
                        <element name="name" type="first:NameType"/>
                        <element name="degree" type="string"/>
                        <element name="DOB" type="date"/>
                        <element name="phone" type="first:PhoneType" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                    <attribute name="ID" type="string"/>
                </complexType>
            </element>
            <element name="dateStarted" type="first:dateOrYearType"/>
        </sequence>
        <attributeGroup ref="first:BlogAttributes"/>
    </complexType>

    <complexType name="NameType">
        <group ref="first:NameGroup"/>
        <attribute name="title" type="string"/>
    </complexType>
    
    <group name="NameGroup">
        <sequence>
            <element name="first" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="middle" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="last" type="string"/>
        </sequence>
    </group>
    
    <complexType name="PhoneType">
        <simpleContent>
            <extension base="string">
                <attribute name="kind" default="Home">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Home"/>
                            <enumeration value="Work"/>
                            <enumeration value="Mobile"/>
                            <enumeration value="Fax"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </simpleContent>
    </complexType>
    
    <attributeGroup name="BlogAttributes">
        <attribute name="tags" type="import:TagsListType"/>
    </attributeGroup>
    
    
</schema>

=== iammisc/zynx-se-bootcamp/xml/modular.xml
<?xml version="1.0" encoding="UTF-8"?>
<blogs
    xmlns="http://www.example.com/modularinclude"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com/modularinclude firstModularSolution.xsd"
    >
    <blog tags="medical health">
        <blogTitle>The Web Doctor</blogTitle>
        <blogger>
            <name title="Dr">
                <first>Steve</first>
                <middle>Michael</middle>
                <last>Patterson</last>
            </name>
            <degree>MD from Harvard Med</degree>
            <DOB>1963-05-27</DOB>
            <phone kind="Work">909-111-1111</phone>
            <phone kind="Mobile">909-222-2222</phone>
        </blogger>
        <dateStarted>1997</dateStarted>
    </blog>
    <blog tags="fitness workout">
        <blogTitle>Get Fit Now!</blogTitle>
        <blogger>
            <name title="Ms.">
                <first>Alexa</first>
                <middle>Lisa</middle>
                <last>Xu</last>
            </name>
            <degree>GED</degree>
            <DOB>1983-01-15</DOB>
            <phone kind="Mobile">909-333-3333</phone>
            <phone kind="Home">909-444-4444</phone>
        </blogger>
        <dateStarted>2007-11-30</dateStarted>
    </blog>
    <blog tags="nutrition diet">
        <blogTitle>Eat Healthy</blogTitle>
        <blogger>
            <name title="Mr.">
                <first>Brian</first>
                <middle>Jack</middle>
                <last>Williams</last>
            </name>
            <degree>B.S. in Nutrition from UCSD</degree>
            <DOB>1975-10-15</DOB>
            <phone kind="Work">909-555-5555</phone>
            <phone kind="Home">909-666-6666</phone>
        </blogger>
        <dateStarted>2000</dateStarted>
    </blog>
</blogs>
