=== iammisc/zynx-se-bootcamp/xml/xmlToSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:questionnaire="http://www.example.com/questionnaire"
    targetNamespace="http://www.example.com/questionnaire"
    elementFormDefault="qualified">
    
    <attributeGroup name="QuestionnaireAttributes">
        <attribute name="version" type="decimal"/>
        <attribute name="comapny" type="string"/>
    </attributeGroup>
    
    <element name="questionnaire">
        <complexType>
            <sequence>
                <element name="participant" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="questionnaire:NameType"/>
                            <element name="sex" type="questionnaire:SexType"/>
                            <element name="DOB" type="date"/>
                            <element name="maritalStatus" type="questionnaire:MaritalStatusType"/>
                            <element name="religion" type="string"/>
                            <element name="phone" type="questionnaire:PhoneType" minOccurs="0" maxOccurs="unbounded"/>
                            <element name="socSec" type="string"/>
                        </sequence>
                        <attribute name="ID" type="string"/>
                    </complexType>
                </element>
            </sequence>
            <attributeGroup ref="questionnaire:QuestionnaireAttributes"/>
        </complexType>
    </element>
    
    <complexType name="NameType">
        <group ref="questionnaire:NameGroup"/>
        <attribute name="title" type="string"/>
    </complexType>
    
    <group name="NameGroup">
        <sequence>
            <element name="first" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="middle" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="last" type="string"/>
        </sequence>
    </group>
    
    <simpleType name="SexType">
        <restriction base="string">
            <enumeration value="male"/>
            <enumeration value="female"/>
            <enumeration value="undisclosed"/>
        </restriction>
    </simpleType>
    
    <simpleType name="MaritalStatusType">
        <restriction base="string">
            <enumeration value="single"/>
            <enumeration value="married"/>
            <enumeration value="divorced"/>
            <enumeration value="widowed"/>
            <enumeration value="undisclosed"/>
        </restriction>
    </simpleType>
    
    <complexType name="PhoneType">
        <simpleContent>
            <extension base="string">
                <attribute name="kind" default="Home">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Home"/>
                            <enumeration value="Work"/>
                            <enumeration value="Mobile"/>
                            <enumeration value="Fax"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </simpleContent>
    </complexType>
    
</schema>

=== iammisc/zynx-se-bootcamp/xml/xmlToSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire
    xmlns="http://www.example.com/questionnaire"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com/questionnaire xmlToSchema.xsd"
    version="1.0"
    comapny="BigNameCo"
    >
    <participant ID="0000001">
            <name title="Mrs.">
                <first>Elizabeth</first>
                <middle>K.</middle>
                <last>Stevenson</last>
            </name>
            <sex>female</sex>
            <DOB>1964-08-24</DOB>
            <maritalStatus>married</maritalStatus>
            <religion>Pastafarian</religion>
            <phone kind="Home">294-867-7723</phone>
            <phone kind="Work">573-193-5839</phone>
            <socSec>11-111-1111</socSec>
    </participant>
    <participant ID="0000002">
            <name title="Mr.">
                <first>Jake</first>
                <middle>V.</middle>
                <last>Whitman</last>
            </name>
            <sex>male</sex>
            <DOB>1962-03-19</DOB>
            <maritalStatus>undisclosed</maritalStatus>
            <religion>Agnostic</religion>
            <phone kind="Home">930-496-1252</phone>
            <phone kind="Mobile">694-293-9927</phone>
            <socSec>22-222-2222</socSec>
    </participant>
    <participant ID="0000003">
        <name title="Ms.">
            <first>Nancy</first>
            <middle>Reanne</middle>
            <last>Patterson</last>
        </name>
        <sex>female</sex>
        <DOB>1942-05-03</DOB>
        <maritalStatus>widowed</maritalStatus>
        <religion>Catholic</religion>
        <phone kind="Home">210-864-2479</phone>
        <phone kind="Fax">285-729-1937</phone>
        <socSec>33-333-3333</socSec>
    </participant>
</questionnaire>
